#!/usr/bin/env node
// CogMemory MCP — Build-time script
// Reads package.json and writes src/version.ts with the current version.

import { readFileSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));

const packageJsonPath = join(__dirname, "..", "package.json");
const versionTsPath = join(__dirname, "..", "src", "version.ts");

const packageJson = JSON.parse(readFileSync(packageJsonPath, "utf-8"));
const version = packageJson.version;

const content = `// AUTO-GENERATED by scripts/generate-version.ts — do not edit manually.
// This file is regenerated on every \`prebuild\` / \`prepublishOnly\` run.
export const VERSION = "${version}";
`;

writeFileSync(versionTsPath, content, "utf-8");
console.log(`[generate-version] src/version.ts → "${version}"`);